health_app/health_app/urls.py
from django.contrib import admin  
from django.urls import path  
from health_metrics import views  
urlpatterns = [  
    path('admin/', admin.site.urls),  
    path('create', views.pat),  
    path('home', views.show),  
    path('edit/<int:id>', views.edit),  
    path('update/<int:id>', views.update),  
    path('delete/<int:id>', views.destroy),  
] 

health_app/health_metrics/models.py
from django.db import models

# Create your models here.
class Patient(models.Model):  
    pid = models.IntegerField()  
    pname = models.CharField(max_length=100)  
    plast_name = models.CharField(max_length=100) 
    page = models.IntegerField()
    pweight = models.IntegerField()
    pheart_rate = models.IntegerField()
    pspo2 = models.IntegerField()
    pestres = models.CharField(max_length = 100)
    class Meta:  
        db_table = "patient"  

health_app/health_metrics/forms.py
from django import forms  
from health_metrics.models import Patient
class PatientForm(forms.ModelForm):  
    class Meta:  
        model = Patient  
        fields = "__all__"  

health_app/health_metrics/views.py
from django.shortcuts import render, redirect  
from health_metrics.forms import PatientForm  
from health_metrics.models import Patient
# Create your views here.  
def pat(request):  
    if request.method == "POST":  
        form = PatientForm(request.POST)  
        if form.is_valid():  
            try:  
                form.save()  
                return redirect('/home')  
            except:  
                pass  
    else:  
        form = PatientForm()  
    return render(request,'index.html',{'form':form})  
def show(request):  
    patients = Patient.objects.all()  
    return render(request,"show.html",{'patients':patients})  
def edit(request, id):  
    patient = Patient.objects.get(id=id)  
    return render(request,'edit.html', {'patient':patient})  
def update(request, id):  
    patient = Patient.objects.get(id=id)  
    form = PatientForm(request.POST, instance = patient)  
    if form.is_valid():  
        form.save()  
        return redirect("/home")  
    return render(request, 'edit.html', {'patient': patient})  
def destroy(request, id):  
    patient = Patient.objects.get(id=id)  
    patient.delete()  
    return redirect("/home")  

health_app/health_metrics/templates/edit.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {# Cargamos la librería #}
    {% comment %} {% load bootstrap4 %} {% endcomment %}
    
    {# CSS Bootstrap #}
    {% comment %} {% bootstrap_css %}  {% endcomment %}
  </head>
  <body>
    <form method="POST" class="post-form" action="/update/{{patient.id}}">
      {% csrf_token %}
      <div class="container">
        <br />
        <div class="row justify-content-center">
          <div class="col-md-12 form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-md-12 col-sm-4">
              <h3 class="font-weight-bold text-center">Update Details</h3>
            </div>
          </div>
          <div class="col-md-12 form-group row">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Id:</label>
            <div class="offset-md-4 col-sm-4">
              <input type="text" name="pid" id="id_pid" required maxlength="20" value="{{ patient.pid }}" />
            </div>
          </div>
          <div class="col-md-12 form-group row">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Name:</label>
            <div class="offset-md-4 col-sm-4">
              <input type="text" name="pname" id="id_pname" required maxlength="100" value="{{ patient.pname }}" />
            </div>
          </div>
          <div class="col-md-12 form-group row">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Last Name:</label>
            <div class="offset-md-4 col-sm-4">
              <input type="text" name="plast_name" id="id_plast_name" required maxlength="100" value="{{ patient.plast_name }}" />
            </div>
          </div>
          <div class="col-md-12 form-group row">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Age:</label>
            <div class="offset-md-4 col-sm-4">
              <input type="number" name="page" id="id_page" required maxlength="2" value="{{ patient.page }}" />
            </div>
          </div>
          <div class="col-md-12 form-group row">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Weight (Kg):</label>
            <div class="offset-md-4 col-sm-4">
              <input type="number" name="pweight" id="id_pweight" required maxlength="5" value="{{ patient.pweight }}" />
            </div>
          </div>
          <div class="col-md-12 form-group row">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Heart Rate (bmp):</label>
            <div class="offset-md-4 col-sm-4">
              <input type="number" name="pheart_rate" id="id_pheart_rate" required maxlength="3" value="{{ patient.pheart_rate }}" />
            </div>
          </div>
          <div class="col-md-12 form-group row">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient SpO2 (%):</label>
            <div class="offset-md-4 col-sm-4">
              <input type="number" name="pspo2" id="id_pspo2" required maxlength="3" value="{{ patient.pspo2 }}" />
            </div>
          </div>
          <div class="col-md-12 form-group row">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Stress Level:</label>
            <div class="offset-md-4 col-sm-4">
              <input type="text" name="pestres" id="id_pestres" required maxlength="100" value="{{ patient.pestres }}" />
            </div>
          </div>
          <div class="col-md-12 form-group row">
            <label class="col-sm-1 col-form-label"></label>
            <div class="offset-md-3 col-sm-4">
              <a href="/home" class="btn btn-warning text-white">Back</a>
              <button type="submit" class="btn btn-success">Update</button>
            </div>
          </div>
        </div>
      </div>
    </form>
    {# JS y jQuery Bootstrap #}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% comment %} {% bootstrap_javascript jquery='full' %} {% endcomment %}
  </body>
</html>

health_app/health_metrics/templates/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Index</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {# Cargamos la librería #}
    {% comment %} {% load bootstrap4 %} {% endcomment %}
    
    {# CSS Bootstrap #}
    {% comment %} {% bootstrap_css %}  {% endcomment %}
  </head>
  <body>
    <form method="POST" class="post-form" action="/create">
      {% csrf_token %}
      <div class="container">
        <br />
        <div class="row justify-content-center">
          <div class="col-md-12 form-group">
            <label class="col-sm-1 col-form-label"></label>
            <div class="col-md-12 col-sm-4">
              <h3 class="font-weight-bold text-center">Enter Details</h3>
            </div>
          </div>
          <div class="col-md-12 form-group">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Id:</label>
            <div class="offset-md-4 col-md-12 col-sm-4">{{ form.pid }}</div>
          </div>
          <div class="col-md-12 form-group">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Name:</label>
            <div class="offset-md-4 col-sm-4">{{ form.pname }}</div>
          </div>
          <div class="col-md-12 form-group">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Last Name:</label>
            <div class="offset-md-4 col-sm-4">{{ form.plast_name }}</div>
          </div>
          <div class="col-md-12 form-group">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Age:</label>
            <div class="offset-md-4 col-sm-4">{{ form.page }}</div>
          </div>
          <div class="col-md-12 form-group">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Weight (Kg):</label>
            <div class="offset-md-4 col-sm-4">{{ form.pweight }}</div>
          </div>
          <div class="col-md-12 form-group">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Heart Rate (bmp):</label>
            <div class="offset-md-4 col-sm-4">{{ form.pheart_rate }}</div>
          </div>
          <div class="col-md-12 form-group">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient SpO2 (%):</label>
            <div class="offset-md-4 col-sm-4">{{ form.pspo2 }}</div>
          </div>
          <div class="col-md-12 form-group">
            <label class="offset-md-4 col-sm-2 col-form-label">Patient Stress Level:</label>
            <div class="offset-md-4 col-sm-4">{{ form.pestres }}</div>
          </div>
          <div class="col-md-12 form-group">
            <label class="col-sm-1 col-form-label"></label>
            <div class="offset-md-4 col-sm-4">
              <a href="/home" class="btn btn-warning text-white">Back</a>
              <button type="submit" class="btn btn-primary">Submit</button>
            </div>
          </div>
        </div>
      </div>
    </form>
    {# JS y jQuery Bootstrap #}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% comment %} {% bootstrap_javascript jquery='full' %}  {% endcomment %}
  </body>
</html>

health_app/health_metrics/templates/show.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Patient Records</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    {# Cargamos la librería #}
    {% comment %} {% load bootstrap4 %} {% endcomment %}
    
    {# CSS Bootstrap #}
    {% comment %} {% bootstrap_css %}  {% endcomment %}
  </head>
  <body>
    <div class="container">
      <div class="col-sm-12">
        <h3 class="text-center font-weight-bold">Patient List</h3>
      </div>
      <table class="table table-striped table-bordered table-sm">
        <thead class="thead-dark">
          <tr>
            <th>Patient ID</th>
            <th>Patient Name</th>
            <th>Patient Last Name</th>
            <th>Patient Age</th>
            <th>Patient Weight (Kg)</th>
            <th>Patient Heart Rate (bmp)</th>
            <th>Patient SpO2 (%)</th>
            <th>Patient Stress Level</th>
            <th width="20%">Actions</th>
          </tr>
        </thead>
        <tbody>
          {% for patient in patients %}
          <tr>
            <td>{{ patient.pid }}</td>
            <td>{{ patient.pname }}</td>
            <td>{{ patient.plast_name }}</td>
            <td>{{ patient.page }}</td>
            <td>{{ patient.pweight }}</td>
            <td>{{ patient.pheart_rate }}</td>
            <td>{{ patient.pspo2 }}</td>
            <td>{{ patient.pestres }}</td>
            <td>
              <div class="btn-group">
                <a class="btn-xs btn-success" href="/edit/{{ patient.id }}">
                  <i class="fa fa-pencil ml-2" aria-hidden="true"></i> <span class="mr-2">Edit</span>
                </a>
                <a class="btn-xs btn-danger" href="/delete/{{ patient.id }}">
                  <i class="fa fa-trash ml-2" aria-hidden="true"></i> <span class="mr-2">Delete</span>
                </a>
              </div>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <br />
    <br />
    <center><a href="/create" class="btn btn-primary">Add New Record</a></center>
    {# JS y jQuery Bootstrap #}
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {% comment %} {% bootstrap_javascript jquery='full' %} {% endcomment %}
  </body>
</html>